language: node_js
node_js:
  - '9'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn build-css
deploy:
  provider: heroku
  api_key:
    develop: "LiNNcovTgaYNR+XG/sLSdCQPk5OfUpBvdl41Xu9/WnxzBDhgHALlDKwD4pA8JzL+sIexcEVVNv569vJgEm6aIMfUHS95lKnSaJ2VzDLtO54SxFdXHwuq804PuYjjKb/btm1JCYqCXMLwGr3ZalcnXQrhoQvfbKtb5Kp4KOIdYM9rULE1Lubmqslfzoy01GXvaKdCU0rgOhyCQvWq1qqtIgzhRYlOy+RzAoYTj98G0hHsSF1ZOlHEpBaHijH+FJf6/hWyp9EPZhyY1NN/dA7JrtACxTldbpelIm7GqfxK3cjRzcQppCVDTcu9NAosmIvxfm8BuYcvb59DYHnt24c5GmT6kJ+vZgGGp776KLUXA3rKgdMi4u0X6N5AP0pjExJUCztg9RNSNUUM7Q8+ta6BgTh/Em2H5HY6vLB/UhfTo5ekYj2rbDI5kFwO4Xn6aREwngzt42JFvzsXaYZP3ZbbViwV5LY5UbXOl/XjV3t6bNy1cuGVfzargjD0o8GZhCraalS/V1Id3R+ggtx0Ovd+hsGM4eioDGgspnyqSWUHLapX+9KlQy8uSeiKhMNvW/5CMAgownjkdqrxvxIAwEvw6EUE3rCbaOUXdfnx9K8/RSv+NM7PmofbnTZd9sDe/CqmAw3N4lnohUHs2+ERFSHBJmCVI5hEGAO3yDCEfIh6JNc="
  app:
    develop: rv-frontend-dev