language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
- yarn build-css
deploy:
  provider: heroku
  api_key:
    develop: "QN3kwoi8nYS+AlHXibMQwIpiKF6RoV63e+Oxr61glgb66OtsTV6kVM1LxiqfM1S7Spje0KFEMhW8yHbreSe+uIkSrnaj8BhGeBCYIyXR4yjrf+YbgrVy0Teseq5vz92ScbTveqyVdHmy+OGqC+GMfAeCPasVJZAKnU8NEGL1QsgAzKDo/Ue+6D81SJblu1Yjm44aTxI8KzMKf5bKuX+ZHY3fOQ9JfdeS2plClBwled/7SSLjy62DSKKfwUdJ5pQ3tWf0i47cjh7L30RaB7/LJzz7dwtvc9kOUforPwdDpB9O/0lJyUDSP2Mf3tHgjh4ZI/Meo8PQbjFBuTlpbgxNgAAIyODEY3uUrn4OIICaPCNf8O1eidyXQvRpLzZiQgHiyQV1Tgw9kr7REiBP1sxOYCRW1UPRE6bog5FF8SdCKYcd1+pf93v2PPtk3znz3Lia4r03W7CqEEpPSBN1Nz8x6kZlTrOWHTYxNV4/B9AGeythvUE7I7hCOioHGI83Hwn/RY/6B8cXoRtMe90CYXyAiv3Msf004Vcd68RrtPF2dBepbUAy5lpkeZ2gvAnncdirlpQFTydhG/u75FsybFKG1Ajm2bXvNiE0Sk2zNqnEZxNro/Vta1smlwVoW/nHmNim5541qp8RjQbDUZQbeHUCm1dT4MVrpu1jqi8eWLr1xt8="
    master: "racJGM0adnUXKzPl90OennUh9jehBCuwglvBdL85Bx/nxvHtjngGO5mnrNq5bnVay8q7T8xlET/uhrhC4k1OkayJpKYNPZTPCjC8v7YH1W3ow4MgNmY/a2adeslc1kkd3abYYyg1iGaqIr7/+2aP3Wyc3pnTko8uNqUQi7WItv/kcCrvuD58Zn9iu/uBTfeuLDq4ASGMTOyuWkQHDo5ra9JUgVwzoxXBWrn/RaxOh/MZZNluvTH5NHjZdmzbinE53sQJVEhdpOjMWjPZsgtSZzrOeZ+KrAwKFBdH8qQDkP83F6bvSyRmEtef1nzFrzuHXTO4NRt8KfdKZWabh0++jmzK/l20xfk3z3IyJACodfdckKftvN6YH283OmhoM2T/dMSV8ZfBqtS3nJ5rj9y/1el51eUo4iW4kzT+hog3uQiW4fCaTLyb3RABtHwyv4RKFrOqFJCQK1MF17furaz/DS3OPLUGqpe2sBHCxAx7cYURnOq8xgr/Y0yxPS8hDQSkciYuUQw4xB2/lEr6gcEde0ynLyL3ifNCB5OoLU/clySM+3wIio1/p5EvDqRp01CQ040k4gkPNi89uZxJMonHzWYkHitprYIA4H/61Ut1yUYROtAGGUbdQupez/kQXniqth2NFNTF466R4iLtw8mOu5LgdbFtOLZ4aTNmpWA4GFA="
  app:
    develop: rv-frontend-dev
    master: rv-frontend