language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
- yarn build-css
deploy:
  provider: heroku
  api_key:
    develop: wUx0Gh4otsekGrWjXumJJMERRJfXJ+M9pgaBXgvYnWNHwomXnSPPf0IpbdH43eEZNUS8v8zslnro3ABHBMOEyF8EA6M3kl/N5hntSIvik/+LVKF9PjT9bVg6DaiQJMlpm9tUi/6dog7oPQWSQMsFk9dEp3Jr4/NGyCVGn9q3dJjrisL0dFkJptnf58NcydYLubdQbiyP1xh7pzeIDujbo18pEcYbWGVklUWjdEsrGFX1aVT/C77wW6/BCL0U6Od5+4taj53lbUWAV8b5jMEgwdV+dK6njMJr4+xGYuhbsFNv3OGwApKktKb9KVqbMWh5G4ha80KXZzk1WRb80dI28zlenI5DgoQwXmIq19cMTNx9cv0U20OnteGAOv2wNcMGLYACopuEalOnpSE10Ni8dwMt5aMH9f1rUCGGJuCZqpFIL2ULRdTds7z4CUn2PFjSz9ggBvopl0/hxtsLgUIaA3HkEwspHNDJH/BUR0/9hsHmvpuDUcr8u83/xSaQPfsyG03bJM5BsELX5c39bFG6j7fnxn99mtj8RadSTl2iQFrtbLDdMkJyF/prr5c6swX/myozXwbzPMieVD5UzTRvYOEBe44mY7F583QjV9KzU/irJ48F35eAg0hRsCWXUwcWiNbW8DcTjrV4usF2LRrC8u9RCaiyZcRUA3ZW5ZNv3H0=
  app:
    develop: rv-frontend-dev
