language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
- yarn build-css
deploy:
  provider: heroku
  api_key:
    secure: E/dC9khxXmleXVANtKWaKlGK/+kaz1K/EUEdDDvCNl6Nn+YRwd48RSj0GD4/h9nnd/0MyWhF7DONEvtpnAW93APc0quaqwCQ6uwFBQBm0q7QtpJx/Xz+0IZvTjYCPpPxp8xBtK2V6fUjZip2vM7UBCPOPumg7HRe3x/K8sfySNgdPjl6xVdtryT7ePC/ZL1VdUHC540iwXU0xOeQQTdIPINd7QaEWRydJ00j5f2n1O8tRiKKtXhfGpPNZjyJIJGIxesUTb/usyGe2nQXbFd4JH8QN9T6q/B0lyC2gPml62RVJfgBT8AY5nRHsZ2VIqgn2RCRHydmHCg8jMNGYF6lG41jcx7pybZQvdVZ7jV22dJgnAcgsMGScGtW9Fvdui1rMaG/Zly0M0jJQ8Jfs4DbBzxTkD0a/X1dP0acdt71qqobHuhJvoh4Q7kr6VXYydU9DJ8HTTewE/J1Q/vP4+HG2tNy88zE2Ijslis8TRBrLv2J3fyX7md+aibVGJykd1qAlhsSqUWJ5Imjx2KEPHyP00CKJmAUJyugCU2bVP1YU37m2jMuT1S1u/zVwwJeU/wloLCvUeoSAa9t5CCBCQe/YqcALifq+jRTNjEkGnpD2JXplMrZTq1RbirGn0IUZHfh1jMA02RKSfLxriWBCFF8UgXK0UMn1mZuT9A0dGARDYs=
  app:
    develop: rv-frontend-dev