language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
- yarn build-css
deploy:
  provider: heroku
  api_key:
    develop: E/dC9khxXmleXVANtKWaKlGK/+kaz1K/EUEdDDvCNl6Nn+YRwd48RSj0GD4/h9nnd/0MyWhF7DONEvtpnAW93APc0quaqwCQ6uwFBQBm0q7QtpJx/Xz+0IZvTjYCPpPxp8xBtK2V6fUjZip2vM7UBCPOPumg7HRe3x/K8sfySNgdPjl6xVdtryT7ePC/ZL1VdUHC540iwXU0xOeQQTdIPINd7QaEWRydJ00j5f2n1O8tRiKKtXhfGpPNZjyJIJGIxesUTb/usyGe2nQXbFd4JH8QN9T6q/B0lyC2gPml62RVJfgBT8AY5nRHsZ2VIqgn2RCRHydmHCg8jMNGYF6lG41jcx7pybZQvdVZ7jV22dJgnAcgsMGScGtW9Fvdui1rMaG/Zly0M0jJQ8Jfs4DbBzxTkD0a/X1dP0acdt71qqobHuhJvoh4Q7kr6VXYydU9DJ8HTTewE/J1Q/vP4+HG2tNy88zE2Ijslis8TRBrLv2J3fyX7md+aibVGJykd1qAlhsSqUWJ5Imjx2KEPHyP00CKJmAUJyugCU2bVP1YU37m2jMuT1S1u/zVwwJeU/wloLCvUeoSAa9t5CCBCQe/YqcALifq+jRTNjEkGnpD2JXplMrZTq1RbirGn0IUZHfh1jMA02RKSfLxriWBCFF8UgXK0UMn1mZuT9A0dGARDYs=
    master: j21aHeDac35b9ahqSGgN8f6kQc/f9e1CKIlUtdIqfaL20EI6IJr2b1Wm/8FOEjS1cxxtQaP8spLmNHOI4DMCHUJO6kwKVe+nejFTBn2PVi5G2EuRcKU6zjw8stBqFn8nFwY41DeAKOCC8+u0kY22WwGPwIeUKlx+byx4hedbOm7Teaz6R5/EuTrsbIWkYixwEvJ+H8arePHxZgc+ou+gbE3GLqCPP5SoihLpov1DiGdibAsbCtQXIa2PPQ3h4wKaNW2hAjgzmhYm10tIRkrpix6eARLaPxqNWButECLZn9lm1n7PvxA0G2V4BMCIiIpgE/LtdzvmcPfyaBJ9ggGPahW2OfQ/O68WqMPGPZnKO6Ha3CwBRj+cRkVGFHCWaXay/hvdw+NsBRBz2cNDwcsp4f4R/9THXAZEg6sbrrW2xqCp4IHOP9Q0XKSlKnqKRoj/Fhln1PgQlS1rCy4IG/Vmph2g37lYrg1wKsjsO5M8fasdY57XPmCdZ+zjRVBrWgXr61Gqiri4/mgLYKdL0VLFYkjAMdv/9ZZhGC21uA2ol8PCT4dXWWLNe4cHLHDYxGGZWUxHW3yKs9YCgYUoP1OkIbjHlxPKJ9mw7KI0ZxNlhYvWv4pM+0SYszWJmIxcdgD6U9177r8fwCCtsytqgmMiCwRDHpalgNMhvzWO43r1Uuw=
  app:
    develop: rv-frontend-dev
    master: rv-frontend